/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CUTd10L07u8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CUTd10L07u8= >>
// ----------- >>
public class Barman extends Staff {
// ----------- << class.extras@AAAAAAF9CUTd10L07u8= >>
// ----------- >>
}