/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CWhJt0S1yrc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CWhJt0S1yrc= >>
// ----------- >>
public class Order {
	// ----------- << attribute.annotations@AAAAAAF9CWwwakcrAN4= >>
	// ----------- >>
	private Double price;

	// ----------- << attribute.annotations@AAAAAAF9CteoARWarSA= >>
	// ----------- >>
	private String note;

	// ----------- << attribute.annotations@AAAAAAF9CWhJ5kTfmuo= >>
	// ----------- >>
	private Waiter waiter;

	// ----------- << attribute.annotations@AAAAAAF9CW2TFkpq5yI= >>
	// ----------- >>
	private Table table;

	// ----------- << attribute.annotations@AAAAAAF9CZJa8W89CLk= >>
	// ----------- >>
	private Set<OrderedItem> food = new HashSet<>();

	public Double getPrice() {
		return price;
	}

	public String getNote() {
		return note;
	}

	public Waiter getWaiter() {
		return waiter;
	}

	public Table getTable() {
		return table;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public void setWaiter(Waiter waiter) {
		this.waiter = waiter;
	}

	public void setTable(Table table) {
		this.table = table;
	}

// ----------- << class.extras@AAAAAAF9CWhJt0S1yrc= >>
// ----------- >>
}