/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CY5DombwW1U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CY5DombwW1U= >>
// ----------- >>
public abstract class Staff extends User {
	// ----------- << attribute.annotations@AAAAAAF9CZXrMnjDnBc= >>
	// ----------- >>
	private Set<OrderedItem> processed = new HashSet<>();

	public Set<OrderedItem> getProcessed() {
		return processed;
	}

// ----------- << class.extras@AAAAAAF9CY5DombwW1U= >>
// ----------- >>
}