/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CYZ1Q1xC0vo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CYZ1Q1xC0vo= >>
// ----------- >>
public enum State {
	free,
	ordered,
	processing,
	finished,
	delivered;

// ----------- << enum.extras@AAAAAAF9CYZ1Q1xC0vo= >>
// ----------- >>
}