/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CThr25WiQC8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CThr25WiQC8= >>
// ----------- >>
public abstract class User {
	// ----------- << attribute.annotations@AAAAAAF9CTm6zpXOvhI= >>
	// ----------- >>
	private Long id;

	// ----------- << attribute.annotations@AAAAAAF9CTs4IpXYIDI= >>
	// ----------- >>
	private String firstName;

	// ----------- << attribute.annotations@AAAAAAF9CTusq5XfqQM= >>
	// ----------- >>
	private String lastName;

	// ----------- << attribute.annotations@AAAAAAF9CTvMrZXmze8= >>
	// ----------- >>
	private String username;

	// ----------- << attribute.annotations@AAAAAAF9CTv7KpXtOHY= >>
	// ----------- >>
	private String password;

	// ----------- << attribute.annotations@AAAAAAF9CTwsvJX0AbA= >>
	// ----------- >>
	private Date dateOfBirth;

	// ----------- << attribute.annotations@AAAAAAF9CTx89JX7n5A= >>
	// ----------- >>
	private Long salary;

	// ----------- << attribute.annotations@AAAAAAF9CYX29lqJGl8= >>
	// ----------- >>
	private Boolean isDeleted;

	public Long getId() {
		return id;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public String getUsername() {
		return username;
	}

	public String getPassword() {
		return password;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public Long getSalary() {
		return salary;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public void setSalary(Long salary) {
		this.salary = salary;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

// ----------- << class.extras@AAAAAAF9CThr25WiQC8= >>
// ----------- >>
}