/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package klase;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>
public class Waiter extends User {
	// ----------- << attribute.annotations@AAAAAAF9CWhJ5kTgti0= >>
	// ----------- >>
	private Set<Order> orders = new HashSet<>();

	public Set<Order> getOrders() {
		return orders;
	}

// ----------- << class.extras@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>
}