/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/


package kts.restaurant_application.controllers;


import javax.validation.Valid;

import kts.restaurant_application.model.Authority;
import kts.restaurant_application.services.AuthorityService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import kts.restaurant_application.model.Admin;
import kts.restaurant_application.services.AdminService;

import java.util.ArrayList;
import java.util.List;

@Transactional
@RestController
@RequestMapping("/admins")
public class AdminController {
    private static final Logger logger = LoggerFactory.getLogger(AdminController.class);

    private final AdminService service;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private AuthorityService authorityService;

    @Autowired
    public AdminController(AdminService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<Admin> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public Admin findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public Admin create(@RequestBody @Valid Admin entity) throws Exception {

        entity.setPassword(passwordEncoder.encode(entity.getPassword()));
        entity.setIsDeleted(false);

        List<Authority> auth = new ArrayList<Authority>();

        auth.add(authorityService.findByName("ROLE_USER"));
        auth.add(authorityService.findByName("ROLE_STAFF"));
        auth.add(authorityService.findByName("ROLE_BARMAN"));

        entity.setAuthorities(auth);

        return service.save(entity);
    }

    @PostMapping("/update")
    public Admin update(@RequestBody Admin entity) throws Exception {
        return service.update(entity);
    }

    @GetMapping("/delete/{id}")
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    public void delete(@PathVariable("id") Long id) throws Exception {
        service.delete(id);
    }
}