/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/


package kts.restaurant_application.controllers;


import javax.validation.Valid;

import kts.restaurant_application.model.Admin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import kts.restaurant_application.model.Cook;
import kts.restaurant_application.services.CookService;

@Transactional
@RestController
@RequestMapping("/cooks")
public class CookController {
    private static final Logger logger = LoggerFactory.getLogger(CookController.class);

    private final CookService service;

    @Autowired
    public CookController(CookService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<Cook> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public Cook findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public Cook create(@RequestBody @Valid Cook entity) {
        return service.save(entity);
    }

    @PutMapping
    public Cook update(@RequestBody Cook entity){
        return service.update(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}