/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.controllers;



import javax.validation.Valid;

import kts.restaurant_application.model.Cook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import kts.restaurant_application.model.Food;
import kts.restaurant_application.services.FoodService;

@Transactional
@RestController
@RequestMapping("/foods")
public class FoodController {
    private static final Logger logger = LoggerFactory.getLogger(FoodController.class);

    private final FoodService service;

    @Autowired
    public FoodController(FoodService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<Food> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public Food findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public Food create(@RequestBody @Valid Food entity) {
        return service.save(entity);
    }

    @PutMapping
    public Food update(@RequestBody Food entity){
        return service.update(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}