/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/



package kts.restaurant_application.controllers;

import javax.validation.Valid;

import kts.restaurant_application.model.Cook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import kts.restaurant_application.model.MainCook;
import kts.restaurant_application.services.MainCookService;

@Transactional
@RestController
@RequestMapping("/mainCooks")
public class MainCookController {
    private static final Logger logger = LoggerFactory.getLogger(MainCookController.class);

    private final MainCookService service;

    @Autowired
    public MainCookController(MainCookService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<MainCook> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public MainCook findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public MainCook create(@RequestBody @Valid MainCook entity) {
        return service.save(entity);
    }

    @PutMapping
    public MainCook update(@RequestBody MainCook entity){
        return service.update(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}