/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/


package kts.restaurant_application.controllers;


import javax.validation.Valid;

import kts.restaurant_application.model.Manager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import kts.restaurant_application.model.OrderedItem;
import kts.restaurant_application.services.OrderedItemService;

@Transactional
@RestController
@RequestMapping("/orderedItems")
public class OrderedItemController {
    private static final Logger logger = LoggerFactory.getLogger(OrderedItemController.class);

    private final OrderedItemService service;

    @Autowired
    public OrderedItemController(OrderedItemService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<OrderedItem> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public OrderedItem findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public OrderedItem create(@RequestBody @Valid OrderedItem entity) {
        return service.save(entity);
    }

    @PutMapping
    public OrderedItem update(@RequestBody OrderedItem entity){
        return service.update(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}