/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.controllers;




import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import kts.restaurant_application.model.Order;
import kts.restaurant_application.model.RestourantTables;
import kts.restaurant_application.model.Waiter;
import kts.restaurant_application.services.OrderService;
import kts.restaurant_application.services.TableService;
import kts.restaurant_application.services.WaiterService;

@Transactional
@RestController
@RequestMapping("/orders")
public class OrderController {
    private static final Logger logger = LoggerFactory.getLogger(OrderController.class);

    private final OrderService service;
    private final TableService tableService;
    private final WaiterService waiterService;

    @Autowired
    public OrderController(OrderService service, TableService t, WaiterService w) {
        this.service = service;
        this.tableService = t;
        this.waiterService = w;
    }

    @GetMapping
    public Iterable<Order> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public Order findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public Order create(@RequestBody @Valid Order entity) {

        RestourantTables t = tableService.findOne(entity.getTable().getId());
        Waiter w = waiterService.findOne(entity.getWaiter().getId());
        entity.setTable(t);
        entity.setWaiter(w);
        return service.save(entity);
    }

    @PutMapping
    public Order update(@RequestBody Order entity){
        return service.update(entity);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}