/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.controllers;



import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import kts.restaurant_application.model.Staff;
import kts.restaurant_application.services.StaffService;

@Transactional
@RestController
@RequestMapping("/staffs")
public class StaffController {
    private static final Logger logger = LoggerFactory.getLogger(StaffController.class);

    private final StaffService service;

    @Autowired
    public StaffController(StaffService service) {
        this.service = service;
    }

    @GetMapping
    public Iterable<Staff> findAll() {
        return service.findAll();
    }

    @GetMapping("/{id}")
    public Staff findOne(@PathVariable("id") Long id) {
        return service.findOne(id);
    }

    @PostMapping
    public Staff create(@RequestBody @Valid Staff entity) {
        return service.save(entity);
    }

    @PostMapping("/update")
    public Staff update(@RequestBody Staff entity){
        return service.update(entity);
    }

    @PostMapping("/delete/{id}")
    public void delete(@PathVariable Long id) {
        service.delete(id);
    }
}