/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.Cook;
import kts.restaurant_application.repositories.CookRepository;

@Service
public class CookService {
    private static final Logger logger = LoggerFactory.getLogger(CookService.class);

    private final CookRepository repository;

    @Autowired
    public CookService(CookRepository repository) {
        this.repository = repository;
    }

    public Iterable<Cook> findAll() {
        return repository.findAll();
    }

    public Cook findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find Cook by " + id));
    }

    public Cook save(Cook entity) {
        return repository.save(entity);
    }

    public void delete(Cook entity) {
        repository.delete(entity);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }
}