/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import kts.restaurant_application.model.Barman;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.Drink;
import kts.restaurant_application.repositories.DrinkRepository;

@Service
public class DrinkService {
    private static final Logger logger = LoggerFactory.getLogger(DrinkService.class);

    private final DrinkRepository repository;

    @Autowired
    public DrinkService(DrinkRepository repository) {
        this.repository = repository;
    }

    public Iterable<Drink> findAll() {
        return repository.findAll();
    }

    public Drink findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find Drink by " + id));
    }

    public Drink save(Drink entity) {
        return repository.save(entity);
    }

    public Drink update(Drink entity){
        Drink existingDrink = findOne(entity.getId());

        existingDrink.setName(entity.getName());
        existingDrink.setDescription(entity.getDescription());
        existingDrink.setPrice(entity.getPrice());
        existingDrink.setPriority(entity.getPriority());
        existingDrink.setSubcategory(entity.getSubcategory());
        existingDrink.setIsDeleted(entity.getIsDeleted());

        return save(existingDrink);
    }



    public void delete(Drink entity) {
        repository.delete(entity);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }
}