/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import kts.restaurant_application.model.Drink;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.Food;
import kts.restaurant_application.repositories.FoodRepository;

@Service
public class FoodService {
    private static final Logger logger = LoggerFactory.getLogger(FoodService.class);

    private final FoodRepository repository;

    @Autowired
    public FoodService(FoodRepository repository) {
        this.repository = repository;
    }

    public Iterable<Food> findAll() {
        return repository.findAll();
    }

    public Food findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find Food by " + id));
    }

    public Food save(Food entity) {
        return repository.save(entity);
    }

    public Food update(Food entity){
        Food existingFood = findOne(entity.getId());

        existingFood.setName(entity.getName());
        existingFood.setDescription(entity.getDescription());
        existingFood.setPrice(entity.getPrice());
        existingFood.setPriority(entity.getPriority());
        existingFood.setSubcategory(entity.getSubcategory());
        existingFood.setIsDeleted(entity.getIsDeleted());

        return save(existingFood);
    }

    public void delete(Food entity) {
        repository.delete(entity);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }
}