/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import kts.restaurant_application.model.Barman;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.MainCook;
import kts.restaurant_application.repositories.MainCookRepository;

import java.util.ArrayList;

@Service
public class MainCookService {
    private static final Logger logger = LoggerFactory.getLogger(MainCookService.class);

    private final MainCookRepository repository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    public MainCookService(MainCookRepository repository) {
        this.repository = repository;
    }

    public Iterable<MainCook> findAll() {
        Iterable<MainCook> all = repository.findAll();
        ArrayList<MainCook> notDeleted = new ArrayList<>();

        for(MainCook b : all){
            if(!b.getIsDeleted()){
                notDeleted.add(b);
            }
        }
        return notDeleted;
    }

    public MainCook findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find MainCook by " + id));
    }

    public MainCook save(MainCook entity) {
        return repository.save(entity);
    }

    public MainCook update(MainCook entity){
        MainCook existingMainCook = findOne(entity.getId());

        existingMainCook.setFirstName(entity.getFirstName());
        existingMainCook.setLastName(entity.getLastName());
        existingMainCook.setPassword(passwordEncoder.encode(entity.getPassword()));
        existingMainCook.setDateOfBirth(entity.getDateOfBirth());
        existingMainCook.setSalary(entity.getSalary());
        existingMainCook.setIsDeleted(entity.getIsDeleted());

        return save(existingMainCook);
    }

    public MainCook delete(MainCook entity) {
        MainCook existingMainCook = findOne(entity.getId());
        existingMainCook.setIsDeleted(true);
        return save(existingMainCook);

    }

    public MainCook delete(Long id) {
        return delete(findOne(id));
    }
}