/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import java.util.Collection;
import java.util.Date;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.OrderedItem;
import kts.restaurant_application.model.State;
import kts.restaurant_application.repositories.OrderedItemRepository;

@Service
public class OrderedItemService {
    private static final Logger logger = LoggerFactory.getLogger(OrderedItemService.class);

    private final OrderedItemRepository repository;

    @Autowired
    public OrderedItemService(OrderedItemRepository repository) {
        this.repository = repository;
    }

    public Iterable<OrderedItem> findAll() {
        return repository.findAll();
    }

    public OrderedItem findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find OrderedItem by " + id));
    }

    public OrderedItem save(OrderedItem entity) {
        if( entity.getId() != null && repository.existsById(entity.getId())){
            throw new ResponseStatusException(HttpStatus.ALREADY_REPORTED, "Ordered item with that id already exists: " + entity.getId());
        }
        entity.setDateTime(new Date());
        return repository.save(entity);
    }

    public OrderedItem update(OrderedItem entity){
        OrderedItem existingOrderedItem = findOne(entity.getId());

        existingOrderedItem.setItem(entity.getItem());
        existingOrderedItem.setDateTime(entity.getDateTime());
        existingOrderedItem.setNumber(entity.getNumber());
        existingOrderedItem.setStaff(entity.getStaff());
        existingOrderedItem.setState(entity.getState());
        existingOrderedItem.setNote(entity.getNote());
        existingOrderedItem.setPrice(entity.getPrice());
        
        return repository.save(existingOrderedItem);
    }

    public boolean delete(OrderedItem entity) {
        if(findOne(entity.getId()) != null && entity.getState() == State.ordered)
        {
            repository.delete(entity);
            return true;
        }
        return false;
    }

    public boolean delete(Long id) {
        return delete(findOne(id));
    }

    public Collection<OrderedItem> getOrderedItemsByItem(Long itemId) {
        return repository.findAllByItemId(itemId);
    }

    public Collection<OrderedItem> getOrderedItemsByDate(Date dateFrom, Date dateTo) {
        return repository.findAllByDateTimeGreaterThanEqualAndDateTimeLessThanEqual(dateFrom, dateTo);
    }
}