/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.services;


import kts.restaurant_application.model.Manager;
import kts.restaurant_application.model.Staff;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import kts.restaurant_application.model.User;
import kts.restaurant_application.repositories.UserRepository;

@Service
public class UserService {
    private static final Logger logger = LoggerFactory.getLogger(UserService.class);

    private final UserRepository repository;

    @Autowired
    public UserService(UserRepository repository) {
        this.repository = repository;
    }

    public Iterable<User> findAll() {
        return repository.findAll();
    }

    public User findOne(Long id) {
        return repository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Cannot find User by " + id));
    }

    public User save(User entity) {
        return repository.save(entity);
    }

    public User update(User entity){
        User existingUser = findOne(entity.getId());

        existingUser.setFirstName(entity.getFirstName());
        existingUser.setLastName(entity.getLastName());
        existingUser.setPassword(entity.getPassword());
        existingUser.setDateOfBirth(entity.getDateOfBirth());
        existingUser.setSalary(entity.getSalary());
        existingUser.setIsDeleted(entity.getIsDeleted());

        return save(existingUser);
    }

    public User delete(User entity) {
        User existingUser = findOne(entity.getId());
        existingUser.setIsDeleted(true);
        return save(existingUser);
    }

    public void delete(Long id) {
        delete(findOne(id));
    }
}