/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;


// ----------- << imports@AAAAAAF9CUWnp0NyeE4= >>
// ----------- >>

@Entity
@Table(name = "_admins")
@PrimaryKeyJoinColumn(name = "user")
// ----------- << class.annotations@AAAAAAF9CUWnp0NyeE4= >>
// ----------- >>
public class Admin extends User {
	public Admin(String firstName, String lastName, String username, String password, Date dateOfBirth, Long salary,
            boolean deleted) {
    }

    // ----------- << equals.annotations@AAAAAAF9CUWnp0NyeE4= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Admin && (getId().equals(((Admin) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUWnp0NyeE4= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 178;
	}

// ----------- << class.extras@AAAAAAF9CUWnp0NyeE4= >>
// ----------- >>
}