/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;


// ----------- << imports@AAAAAAF9CUTd10L07u8= >>
// ----------- >>

@Entity
@Table(name = "_barmen")
@PrimaryKeyJoinColumn(name = "staff")
// ----------- << class.annotations@AAAAAAF9CUTd10L07u8= >>
// ----------- >>
public class Barman extends Staff {
	// ----------- << equals.annotations@AAAAAAF9CUTd10L07u8= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Barman && (getId().equals(((Barman) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUTd10L07u8= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 451;
	}

// ----------- << class.extras@AAAAAAF9CUTd10L07u8= >>
// ----------- >>
}