/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;


// ----------- << imports@AAAAAAF9CUTaZkK6UQ0= >>
// ----------- >>

@Entity
@Table(name = "_cooks")
@PrimaryKeyJoinColumn(name = "staff")
// ----------- << class.annotations@AAAAAAF9CUTaZkK6UQ0= >>
// ----------- >>
public class Cook extends Staff {
	// ----------- << equals.annotations@AAAAAAF9CUTaZkK6UQ0= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Cook && (getId().equals(((Cook) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUTaZkK6UQ0= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 611;
	}

// ----------- << class.extras@AAAAAAF9CUTaZkK6UQ0= >>
// ----------- >>
}