///*
//* This code has been generated by the Rebel: a code generator for modern Java.
//*
//* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
//*/
//package klase;
//
//import java.util.*;
//import java.time.*;
//
//
//
//// ----------- << imports@AAAAAAF9CYNzuFNUgjE= >>
//// ----------- >>
//
//// ----------- << class.annotations@AAAAAAF9CYNzuFNUgjE= >>
//// ----------- >>
//public class Food extends Item {
//// ----------- << class.extras@AAAAAAF9CYNzuFNUgjE= >>
//// ----------- >>
//}