/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name="food_table")
public class Food extends Item {

    public Food(Long id, Double price,String name, Byte priority, String subcategory, String description, boolean isDeleted) {
        super(id, price,name, priority, subcategory, description, isDeleted);
    }

    public Food() {
    }
}