/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;



import javax.persistence.*;

@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class Item {

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long id;

	@Column(unique = false, nullable = false)
	private String name;

	@Column(unique = false, nullable = true)
	private Double price;

	@Column(unique = false, nullable = true)
	private Byte priority;

	@Column(unique = false, nullable = true)
	private String subcategory;

	@Column(unique = false, nullable = true)
	private String description;

	@Column(unique = false, nullable = false)
	private boolean isDeleted;

	public Item(Long id, Double price, String name, Byte priority, String subcategory, String description, boolean isDeleted) {
		this.id = id;
		this.price = price;
		this.name = name;
		this.priority = priority;
		this.subcategory = subcategory;
		this.description = description;
		this.isDeleted = isDeleted;
	}

	public Item() {
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getId() {
		return id;
	}

	public Double getPrice() {
		return price;
	}

	public Byte getPriority() {
		return priority;
	}

	public String getSubcategory() {
		return subcategory;
	}

	public String getDescription() {
		return description;
	}

	public boolean getIsDeleted() {
		return isDeleted;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	public void setSubcategory(String subcategory) {
		this.subcategory = subcategory;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}


}