/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import io.swagger.annotations.ApiModel;

// ----------- << imports@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>

@Entity
@Table(name = "_items")
@Inheritance(strategy = InheritanceType.JOINED)
@JsonTypeInfo(
		use = JsonTypeInfo.Id.NAME,
		property = "type"
)
@JsonSubTypes({
		@JsonSubTypes.Type(value = Food.class, name = "food"),
		@JsonSubTypes.Type(value = Drink.class, name = "drink")
})
@ApiModel(description = "")
// ----------- << class.annotations@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>
public abstract class Item {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	// ----------- << id.annotations@AAAAAAF9CXDQAE7PULE= >>
	// ----------- >>
	private Long id;

	@Version
	// ----------- << version.annotations@AAAAAAF9CXDQAE7PULE= >>
	// ----------- >>
	private Long version;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CX8wfk9mP/U= >>
	// ----------- >>
	private Double price;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CX/L7VDv7lE= >>
	// ----------- >>
	private Byte priority;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CYJVzFIUNmo= >>
	// ----------- >>
	private String subcategory;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CYKyxVJFCAE= >>
	// ----------- >>
	private String description;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CYZLHluBVmQ= >>
	// ----------- >>
	private Boolean isDeleted;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9KMCEXrsYSmk= >>
	// ----------- >>
	private String name;

	// ----------- << getId.annotations@AAAAAAF9CXDQAE7PULE= >>
	// ----------- >>
	public Long getId(){
		return id;
	}

	public Double getPrice() {
		return price;
	}

	public Byte getPriority() {
		return priority;
	}

	public String getSubcategory() {
		return subcategory;
	}

	public String getDescription() {
		return description;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public String getName() {
		return name;
	}

	public Item setPrice(Double price) {
		this.price = price;
		return this;
	}

	public Item setPriority(Byte priority) {
		this.priority = priority;
		return this;
	}

	public Item setSubcategory(String subcategory) {
		this.subcategory = subcategory;
		return this;
	}

	public Item setDescription(String description) {
		this.description = description;
		return this;
	}

	public Item setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
		return this;
	}

	public Item setName(String name) {
		this.name = name;
		return this;
	}

	// ----------- << equals.annotations@AAAAAAF9CXDQAE7PULE= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Item && (getId().equals(((Item) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CXDQAE7PULE= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 293;
	}

// ----------- << class.extras@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>
}