/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


// ----------- << imports@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>
public class Item {
	// ----------- << attribute.annotations@AAAAAAF9CX8dkk81xo0= >>
	// ----------- >>
	private Long id;

	// ----------- << attribute.annotations@AAAAAAF9CX8wfk9mP/U= >>
	// ----------- >>
	private Double price;

	// ----------- << attribute.annotations@AAAAAAF9CX/L7VDv7lE= >>
	// ----------- >>
	private Byte priority;

	// ----------- << attribute.annotations@AAAAAAF9CYJVzFIUNmo= >>
	// ----------- >>
	private String subcategory;

	// ----------- << attribute.annotations@AAAAAAF9CYKyxVJFCAE= >>
	// ----------- >>
	private String description;

	// ----------- << attribute.annotations@AAAAAAF9CYZLHluBVmQ= >>
	// ----------- >>
	private Boolean isDeleted;

	public Long getId() {
		return id;
	}

	public Double getPrice() {
		return price;
	}

	public Byte getPriority() {
		return priority;
	}

	public String getSubcategory() {
		return subcategory;
	}

	public String getDescription() {
		return description;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	public void setSubcategory(String subcategory) {
		this.subcategory = subcategory;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

// ----------- << class.extras@AAAAAAF9CXDQAE7PULE= >>
// ----------- >>
}