/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import java.util.Date;
import java.util.Set;

// ----------- << imports@AAAAAAF9CUX8xkOuVTY= >>
// ----------- >>

@Entity
@Table(name = "_mainCooks")
@PrimaryKeyJoinColumn(name = "cook")
// ----------- << class.annotations@AAAAAAF9CUX8xkOuVTY= >>
// ----------- >>
public class MainCook extends Cook {

	public MainCook() {
	}

	public MainCook(String firstName, String lastName, String username, String password, Date dateOfBirth, Long salary, boolean deleted, Set<OrderedItem> processed) {
		super(firstName, lastName, username, password, dateOfBirth, salary, deleted, processed);
	}

	// ----------- << equals.annotations@AAAAAAF9CUX8xkOuVTY= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof MainCook && (getId().equals(((MainCook) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUX8xkOuVTY= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 368;
	}

// ----------- << class.extras@AAAAAAF9CUX8xkOuVTY= >>
// ----------- >>
}