/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;




// ----------- << imports@AAAAAAF9CUTSP0KAdFo= >>
// ----------- >>

@Entity
@Table(name = "_managers")
@PrimaryKeyJoinColumn(name = "user")
// ----------- << class.annotations@AAAAAAF9CUTSP0KAdFo= >>
// ----------- >>
public class Manager extends User {
	// ----------- << equals.annotations@AAAAAAF9CUTSP0KAdFo= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Manager && (getId().equals(((Manager) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUTSP0KAdFo= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 18;
	}

// ----------- << class.extras@AAAAAAF9CUTSP0KAdFo= >>
// ----------- >>
}