/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModel;


// ----------- << imports@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>

@Entity
@Table(name = "_tables")
@ApiModel(description = "")
// ----------- << class.annotations@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>
public class RestourantTables {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	// ----------- << id.annotations@AAAAAAF9CW0q1EmSAHg= >>
	// ----------- >>
	private Long id;

	@Version
	// ----------- << version.annotations@AAAAAAF9CW0q1EmSAHg= >>
	// ----------- >>
	private Long version;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CW8E1U0hHSY= >>
	// ----------- >>
	private Long tableNumber;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CW8gvk1Svcg= >>
	// ----------- >>
	private Integer floor;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CW9z+E2D86M= >>
	// ----------- >>
	private Double positionX;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CW+1Xk20/84= >>
	// ----------- >>
	private Double positionY;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CW/SyE3ltLQ= >>
	// ----------- >>
	private State state;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAF9CYYmuVreRBs= >>
	// ----------- >>
	private Boolean isDeleted;

	@OneToMany(mappedBy = "table")
	// ----------- << attribute.annotations@AAAAAAF9CW2TFkppPQk= >>
	// ----------- >>
	private Set<Order> orders = new HashSet<>();

	// ----------- << getId.annotations@AAAAAAF9CW0q1EmSAHg= >>
	// ----------- >>
	public Long getId(){
		return id;
	}

	public Long getTableNumber() {
		return tableNumber;
	}

	public Integer getFloor() {
		return floor;
	}

	public Double getPositionX() {
		return positionX;
	}

	public Double getPositionY() {
		return positionY;
	}

	public State getState() {
		return state;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public Set<Order> getOrders() {
		return orders;
	}

	public RestourantTables setTableNumber(Long tableNumber) {
		this.tableNumber = tableNumber;
		return this;
	}

	public RestourantTables setFloor(Integer floor) {
		this.floor = floor;
		return this;
	}

	public RestourantTables setPositionX(Double positionX) {
		this.positionX = positionX;
		return this;
	}

	public RestourantTables setPositionY(Double positionY) {
		this.positionY = positionY;
		return this;
	}

	public RestourantTables setState(State state) {
		this.state = state;
		return this;
	}

	public RestourantTables setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
		return this;
	}

	public RestourantTables linkOrders(Order _orders) {
		if (_orders != null) {
			_orders.unlinkTable();
			_orders.setTable(this);
			getOrders().add(_orders);
		}
		return this;
	}

	public RestourantTables unlinkOrders(Order _orders) {
		if (_orders != null) {
			_orders.setTable(null);
			getOrders().remove(_orders);
		}
		return this;
	}

	public RestourantTables unlinkOrders(Order _orders, Iterator<Order> it) {
		if (_orders != null) {
			_orders.setTable(null);
			it.remove();
		}
		return this;
	}

	// ----------- << equals.annotations@AAAAAAF9CW0q1EmSAHg= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof RestourantTables && (getId().equals(((RestourantTables) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CW0q1EmSAHg= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 115;
	}

// ----------- << class.extras@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>
}