/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;


// ----------- << imports@AAAAAAF9CY5DombwW1U= >>
// ----------- >>

@Entity
@Table(name = "_staff")
@PrimaryKeyJoinColumn(name = "user")
// ----------- << class.annotations@AAAAAAF9CY5DombwW1U= >>
// ----------- >>
public abstract class Staff extends User {
	@OneToMany(mappedBy = "staff")
	// ----------- << attribute.annotations@AAAAAAF9CZXrMnjDnBc= >>
	// ----------- >>
	private Set<OrderedItem> processed = new HashSet<>();

	public Set<OrderedItem> getProcessed() {
		return processed;
	}

	public Staff linkProcessed(OrderedItem _processed) {
		if (_processed != null) {
			_processed.unlinkStaff();
			_processed.setStaff(this);
			getProcessed().add(_processed);
		}
		return this;
	}

	public Staff unlinkProcessed(OrderedItem _processed) {
		if (_processed != null) {
			_processed.setStaff(null);
			getProcessed().remove(_processed);
		}
		return this;
	}

	public Staff unlinkProcessed(OrderedItem _processed, Iterator<OrderedItem> it) {
		if (_processed != null) {
			_processed.setStaff(null);
			it.remove();
		}
		return this;
	}

	// ----------- << equals.annotations@AAAAAAF9CY5DombwW1U= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Staff && (getId().equals(((Staff) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CY5DombwW1U= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 307;
	}

// ----------- << class.extras@AAAAAAF9CY5DombwW1U= >>
// ----------- >>
}