/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;

// ----------- << imports@AAAAAAF9CYSjsVU7Zgg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CYSjsVU7Zgg= >>
// ----------- >>
public enum Status {
	active,
	inactive;

// ----------- << enum.extras@AAAAAAF9CYSjsVU7Zgg= >>
// ----------- >>
}