/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;

// ----------- << imports@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>
public class Table {
	// ----------- << attribute.annotations@AAAAAAF9CW5vHkyO+Y0= >>
	// ----------- >>
	private Long id;

	// ----------- << attribute.annotations@AAAAAAF9CW8E1U0hHSY= >>
	// ----------- >>
	private Long tableNumber;

	// ----------- << attribute.annotations@AAAAAAF9CW8gvk1Svcg= >>
	// ----------- >>
	private Integer floor;

	// ----------- << attribute.annotations@AAAAAAF9CW9z+E2D86M= >>
	// ----------- >>
	private Double positionX;

	// ----------- << attribute.annotations@AAAAAAF9CW+1Xk20/84= >>
	// ----------- >>
	private Double positionY;

	// ----------- << attribute.annotations@AAAAAAF9CW/SyE3ltLQ= >>
	// ----------- >>
	private State state;

	// ----------- << attribute.annotations@AAAAAAF9CYYmuVreRBs= >>
	// ----------- >>
	private Boolean isDeleted;

	// ----------- << attribute.annotations@AAAAAAF9CW2TFkppPQk= >>
	// ----------- >>
	// private Set<Order> orders = new HashSet<>();

	public Long getId() {
		return id;
	}

	public Long getTableNumber() {
		return tableNumber;
	}

	public Integer getFloor() {
		return floor;
	}

	public Double getPositionX() {
		return positionX;
	}

	public Double getPositionY() {
		return positionY;
	}

	public State getState() {
		return state;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	// public Set<Order> getOrders() {
	// 	return orders;
	// }

	public void setId(Long id) {
		this.id = id;
	}

	public void setTableNumber(Long tableNumber) {
		this.tableNumber = tableNumber;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public void setPositionX(Double positionX) {
		this.positionX = positionX;
	}

	public void setPositionY(Double positionY) {
		this.positionY = positionY;
	}

	public void setState(State state) {
		this.state = state;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

// ----------- << class.extras@AAAAAAF9CW0q1EmSAHg= >>
// ----------- >>
}