/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package kts.restaurant_application.model;


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;


// ----------- << imports@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>

@Entity
@Table(name = "_waiters")
@PrimaryKeyJoinColumn(name = "user")
// ----------- << class.annotations@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>
public class Waiter extends User {
	@OneToMany(mappedBy = "waiter")
	// ----------- << attribute.annotations@AAAAAAF9CWhJ5kTgti0= >>
	// ----------- >>
	private Set<Order> orders = new HashSet<>();

	public Set<Order> getOrders() {
		return orders;
	}

	public Waiter linkOrders(Order _orders) {
		if (_orders != null) {
			_orders.unlinkWaiter();
			_orders.setWaiter(this);
			getOrders().add(_orders);
		}
		return this;
	}

	public Waiter unlinkOrders(Order _orders) {
		if (_orders != null) {
			_orders.setWaiter(null);
			getOrders().remove(_orders);
		}
		return this;
	}

	public Waiter unlinkOrders(Order _orders, Iterator<Order> it) {
		if (_orders != null) {
			_orders.setWaiter(null);
			it.remove();
		}
		return this;
	}

	// ----------- << equals.annotations@AAAAAAF9CUTlN0Mu/lU= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Waiter && (getId().equals(((Waiter) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAF9CUTlN0Mu/lU= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 38;
	}

// ----------- << class.extras@AAAAAAF9CUTlN0Mu/lU= >>
// ----------- >>
}