/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

package kts.restaurant_application.repositories;

import java.util.Collection;
import java.util.Date;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import kts.restaurant_application.model.OrderedItem;

@Repository
public interface OrderedItemRepository extends JpaRepository<OrderedItem, Long> {

    Collection<OrderedItem> findAllByItemId(Long id);
    Collection<OrderedItem> findAllByDateTimeGreaterThanEqualAndDateTimeLessThanEqual(Date dateFrom, Date dateTo);


}